modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    displayURL = "${mod_url}"
    logoFile = "icon.png"
    authors = "${mod_author}"

    [[dependencies.${mod_id}]]
        modId = "forge"
        mandatory = true
        versionRange = "[${forge_version},)"
        ordering = "NONE"
        side = "BOTH"
    [[dependencies.${mod_id}]]
        modId = "minecraft"
        mandatory = true
        versionRange = "[${minecraft_version},)"
        ordering = "NONE"
        side = "BOTH"
    [[dependencies.${mod_id}]]
        modId = "gtceu"
        mandatory = true
        versionRange = "[${gtceu_version},)"
        ordering = "AFTER"
        side = "BOTH"
    [[dependencies.${mod_id}]]
        modId = "ad_astra"
        mandatory = false
        versionRange = "[1.15.19,)"
        ordering = "AFTER"
        side = "BOTH"

